.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2022 UnionTech Software Technology Co., Ltd,
.\"
.TH "com.deepin.lianliankan" "1" "2021-8-11" "Deepin"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
com.deepin.lianliankan \- lianliankan game for deepin.
.SH SYNOPSIS
com.deepin.lianliankan [OPTIONS...]
.SH DESCRIPTION
Lianliankan is a puzzle game.
.PP
Lianliankan is an easy-to-play puzzle game with cute interface and countdown timer.
.SH OPTIONS
.PP
Note: file(s) + command
.PP
-h,--help      Displays this help.
.PP
-v,--version   Displays version information.
.SH SEE ALSO
https://github.com/linuxdeepin/com.deepin.lianliankan
.SH AUTHOR
.PP
.B com.deepin.lianliankan
is written by Deepin Technology Co., Ltd.
.PP
This manual page was written by
.MT linxun@\:uniontech.com
Lin Xun
.ME
for the Debian Project (but may be used by others)
